create table seckill_event (
    id bigint generated by default as identity primary key,
    name varchar(128) not null,
    start_time timestamp not null,
    end_time timestamp not null,
    total_stock integer not null,
    available_stock integer not null,
    version bigint not null default 0
);

create table purchase_order (
    id bigint generated by default as identity primary key,
    order_no varchar(64) not null,
    event_id bigint not null,
    user_id varchar(64) not null,
    created_at timestamp not null,
    constraint uk_purchase_order_order_no unique (order_no),
    constraint uk_purchase_order_event_user unique (event_id, user_id),
    constraint fk_purchase_order_event foreign key (event_id) references seckill_event(id)
);

create index idx_purchase_order_event_created_at on purchase_order(event_id, created_at);

create table seckill_purchase_request (
    id bigint generated by default as identity primary key,
    request_id varchar(64) not null,
    event_id bigint not null,
    user_id varchar(64) not null,
    status varchar(16) not null,
    redis_reserved boolean not null,
    failure_code varchar(64),
    failure_message varchar(255),
    order_id bigint,
    order_no varchar(64),
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint uk_request_request_id unique (request_id),
    constraint uk_request_event_user unique (event_id, user_id)
);

create index idx_request_status_updated_at on seckill_purchase_request(status, updated_at);
create index idx_request_event_created_at on seckill_purchase_request(event_id, created_at);
