create table redis_compensation_task (
    id bigint generated by default as identity primary key,
    event_id bigint not null,
    user_id varchar(64) not null,
    source varchar(32) not null,
    status varchar(16) not null,
    attempt_count integer not null,
    last_error_message varchar(255),
    next_retry_at timestamp not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint uk_redis_comp_task_event_user unique (event_id, user_id)
);

create index idx_redis_comp_task_status_next_retry on redis_compensation_task(status, next_retry_at);
